[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  OPENAI_API_KEY = "${OPENAI_API_KEY}"
  OPENAI_ORG_ID = "${OPENAI_ORG_ID}"
  VITE_API_URL = "/.netlify/functions/chat"
  VITE_ENABLE_STREAMING = "true"
  VITE_ENABLE_DEBUG_LOGGING = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data:; worker-src 'self' blob:;"
